### ISSUE TITLE
[QUESTION] How to explicitly setting the averaging method in HEMCO_Diagn.rc?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#108]
Hi GCST,

I have read your description on [HEMCO diagnostics](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User's_Guide#Diagnostics), but get a little bit confused on how to explicitly setting the averaging method to obtain such as sum (total sum over the output interval).

In the Overview subsection, it is said that we can explicitly set the averaging method for each diagnostic container to obtain such as sum (total sum over the output interval).

However, in the Diagnostic input file subsection, it shows only 7 entries to define a diagnostic container. This is also the case for the default HEMCO_Diagn.rc file which I downloaded from your site.

So my question is that is it possible and how to explicitly setting the averaging method to obtain such as sum (total sum over the output interval) expressed in kg for each grid box?

Many thanks in advance!

All the best,
Fei

**Comment by christophkeller** [comment]
Hi Fei,
unless this has changed with some of the latests HEMCO updates, you should be able to simply set the output unit in HEMCO_Diagn.rc to 'kg' (instead of 'kg/m2's') and it will output the accumulated total emission per grid cell for those diagnostics.
You can also easily calculate the total for each grid cell in a post-processing step by multiplying the default output (in kg/m2/s) by the averaging time interval and the grid cell areas. 

Best,
Christoph

**Comment by FeiYao-Edinburgh** [comment]
Thanks @christophkeller ! Further, I wonder setting the output unit to "kg" should give me accumulated total emission per grid cell <b>over the output interval</b>? I have this confusion because in the Overview subsection, there is also a cumulsum (cumulative sum since simulation start).

**Comment by christophkeller** [comment]
It will give you the total emission since the last diagnostics was written. For instance, if the diagnostics are written every hour it will give you the total emissions for the given hour. The diagnostics are reset to zero after they are being written out. The cumsum option is a lower-level function that can be used inside the HEMCO main code if one wanted to accumulate the values over the entire simulation period instead. I don't think this option is currently used anywhere in GEOS-Chem.

**Comment by FeiYao-Edinburgh** [comment]
Thanks a lot @christophkeller !
