### ISSUE TITLE
[QUESTION] Several small questions on descriptions of sourceTime and CRE

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#14]
Hi there,

I have seen your [HEMCO user guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide) and would be grateful if you help me address the following concerns on sourceTime and CRE.

I suppose there are three items that we need to keep in mind.
1. datetime of the input file
2. source time attribute, which specifies time slices to be used and data refresh frequency.
3. current simulate time

I believe the main logic of HEMCO determining which date of data to be used is as follows.

1. Compare the current simulation time (3) with source time attribute (2). 
1.1 Supposing (3) is inside (2), go to 2.
1.1 Supposing (3) is outside (2), use the most likely datetime if CRE == C or the model halts with an error if CRE == RE.
2. Compare the datetime determined from step 1 (2) with the datetime of the input file (1).
2.1 Supposing (2) is inside (1), everything is fine.
2.2 Supposing (2) is outside (1), only use the most likely datetime?

So you see the main logic sequence is (3)->(2)->(1). My questions are:
1. CRE only works for (3)->(2)? (I believe the answer is YES as I now see "CRE Controls the time slice if the simulation date is outside the range provided in attribute source time.")
2. **If (2) is outside (1), do we ONLY apply the 'most likely' scheme for addressing it?**

Supposing my guess is right, would it be great to edit the following descriptions in your wiki? (please see bold texts)

> C (cycling): Data are interpreted as climatology and recycled once the end of the last time slice is reached. For instance, if the input data contains monthly data of year 2000, and the source time attribute is set to 2000/1-12/1/0 C, the same monthly data will be re-used every year. If the input data spans multiple years (e.g. monthly data from 2000-2003), the closest available year will be used outside of the available range (e.g. the monthly data of 2003 is used for all simulation years after 2003).
- C (cycling): Data are interpreted as climatology and recycled once the end of the last time slice is reached. For instance, if the input data contains monthly data of year 2000, and the source time attribute is set to 2000/1-12/1/0 C, the same monthly data will be re-used every year. If the input data spans multiple years (e.g. monthly data from 2000-2003)**, and the source time attribute is set to 2000-2003/1-12/1/0 C,** the closest available year will be used outside of the available range (e.g. the monthly data of 2003 is used for all simulation years after 2003).

> R (range): Data are only considered as long as the simulation time is within the time range specified in attribute sourceTime. The provided range does not necessarily need to match the time stamps of the input file. If it is outside of the range of the netCDF time stamps, the closest available date will be used. For instance, if a file contains data for years 2003 to 2010 and the provided range is set to 2006-2010/1/1/0 R, the file will only be considered between simulation years 2006-2010. For simulation years 2006 through 2009, the corresponding field on the file is used. For all years beyond 2009, data of year 2010 is used. If the simulation date is outside the provided time range, the data is ignored but HEMCO does not return an error - the field is simply treated as empty (a corresponding warning is issued in the HEMCO log file). For example, if the source time attribute is set to 2000-2002/1-12/1/0 R, the data will be used for simulation years 2000 to 2002 and ignored for all other years.
- R (range): Data are only considered as long as the simulation time is within the time range specified in attribute sourceTime. The provided range does not necessarily need to match the time stamps of the input file. If it is outside of the range of the netCDF time stamps, the closest available date will be used. For instance, if a file contains data for years 2003 to 2010 and the provided range is set to 2006-**2013**/1/1/0 R, the file will only be considered between simulation years 2006-**2013**. For simulation years 2006 through 2009, the corresponding field on the file is used. For all years **after** 2009, data of year 2010 is used. If the simulation date is outside the provided time range, the data is ignored but HEMCO does not return an error - the field is simply treated as empty (a corresponding warning is issued in the HEMCO log file). For example, if the source time attribute is set to 2000-2002/1-12/1/0 R, the data will be used for simulation years 2000 to 2002 and ignored for all other years.

Thanks in advance for your help!

Yours faithfully,
Fei

**Comment by msulprizio** [comment]
Sorry for the late reply. We have just released [HEMCO-3.0.0-rc.0](https://github.com/geoschem/HEMCO/releases/tag/3.0.0-rc.0) and are in the process of moving the HEMCO documentation to hemco.readthedocs.io. At the moment that link only includes the basics of getting started with the HEMCO standalone, but we plan to migrate most of the HEMCO user guide text from the GEOS-Chem wiki there. We will also be updating the clarifying the text in the existing HEMCO user's guide on the wiki.

> CRE only works for (3)->(2)? (I believe the answer is YES as I now see "CRE Controls the time slice if the simulation date is outside the range provided in attribute source time.")

That is correct. The CRE flag only addresses differences between the current simulation time and the source time attribute specified in HEMCO_Config.rc.

> If (2) is outside (1), do we ONLY apply the 'most likely' scheme for addressing it?

Ideally, the source time attribute in HEMCO_Config.rc (2) should not differ from the datetime in the input file. If (2) is outside of (1) and CRE flag of `C` is used, the closes available time from the input file will be used. If a CRE flag with `R` or `E` is used, the simulation will crash because it cannot find the datetime in the input file.

If you are ever in doubt about how HEMCO handles data selection, we recommend you set both Verbose and Warnings to 3 in `HEMCO_Config.rc` and run a short simulation. The resulting HEMCO.log file will include information about the available dates and times in the input file, the preferred time that HEMCO would like to use, and the selected time used.

**Comment by FeiYao-Edinburgh** [comment]
I feel satisfied with the reply and close the issue myself. Thanks!
