### ISSUE TITLE
[QUESTION] Apply scale factor only on given year, otherwise skip?

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/HEMCO#35]
Hi,

I’ve been using HEMCO standalone to setup an experiment with some scaling of emissions data on v12.6.0. I’m having problems trying to apply scale factors to some monthly emissions data. The emissions are for one year (2019), but need reusing in 2020, so they’re set to cycling:

'0  HCOOH_WT              $EMISDIR/WST/NMVOC_HCOOH.0.1x0.1.nc               emi_HCOOH          2019/1-12/1/0    C      xy        kg/m2/s    HCOOH 26/504              1    1000'

'504 NMVOC_MNTHLY     $SF_DIR/NMVOC_monthly.nc     emi_nmvoc       2020/1-12/1/0  CY    xy                1       1'

Scale factor 504 contains a 0.1x0.1grid of monthly scale factors for that species, for 2020. So for 2019 s.f 504 should be ignored/skipped.

I keep having problems with getting the intended result. I think the issue is that the emission year setting is being used to select the scale factor time. I’ve tried experimenting with the CRE attribute and have also added monthly scale factors of 1 for each month of 2019 to s.f 504, but this doesn’t seem to work. 

Do you have any suggestions?

**Comment by msulprizio** [comment]
You should be able to address this by modifying the time cycle (CRE) flag. For your 2020 scale factor, you have the time cycle flag set to `CY`, which tells HEMCO to "cycle" or use the closest year available. I believe you want to use `R` instead, which tells HEMCO to only apply the data during the specified date range -- in your case for the year 2020 and month 1-12. 

You may also need to change the date string for your data entry from `2019/1-12/1/0' to '2019-2020/1-12/1/0` so that HEMCO recomputes the emissions fields for 2020 using the scale factors. 

Finally, I'd recommend you set Verbose and Warnings to `3` at the top of HEMCO_Config.rc for your debugging runs. Those settings will produce more information in the HEMCO.log file so you can see exactly how HEMCO is handling the data.

**Comment by LukeFakes** [comment]
Thanks, that's worked perfectly!
