### ISSUE TITLE
[FEATURE REQUEST] Finish adding CMakeLists to build the HEMCO standalone

### ISSUE THREAD

**Issue by yantosca** [geoschem/HEMCO#6]
The CMakeLists in this repository are somewhat incomplete.  It would be great to make whatever modifications so that CMake can build the HEMCO standalone from this repository so that we don't have to rely on GNU Make.

**Comment by msulprizio** [comment]
I have started working on this. My first step was to copy CMakeLists.txt and the CMakeScripts directory from https://github.com/geoschem/geos-chem top-level directory. I've started changing references to "GEOS-Chem"/"GC" to "HEMCO". My plan is to modify the CMake files from there to compile the HEMCO standalone. However, we need to think ahead as this repository won't be used for just the HEMCO standalone but will also be used for the HEMCO Git submodule in GEOS-Chem, GCHP, GEOS, CESM, and other models starting in GEOS-Chem 13.0.0/HEMCO 3.0.0. 

@LiamBindle Any advice before I get too deep?

**Comment by LiamBindle** [comment]
@msulprizio That sounds good to me. I guess the only thing I'd suggest is avoiding GC-Helpers.cmake and something like GC-ConfigureClassic.cmake if you can. I think they're still necessary for geos-chem because of all the compile-time options, but if you can get away without analogs of these two files, I think that would benefit future-proofing HEMCO's CMakeLists.

**Comment by yantosca** [comment]
I believe this is now completed.  The HEMCO standalone can be built using CMake alone from the HEMCO repository.
