### ISSUE TITLE
[QUESTION]The emission year setting does not work 

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/HEMCO#75]
thank you, @yantosca .I follow you said the following settings: But the statement not seem to work, still reading the same year emissions with the meteorological field, I do not know why.Actually I want to use a different year emissions. 
```
ROOT: /GEOS_chem/gc-data/ExtData/HEMCO
METDIR: /GEOS_chem/gc-data/ExtData/GEOS_2x2.5/MERRA2
Logfile: HEMCO.log
DiagnFile: HEMCO_Diagn.rc
DiagnPrefix: ./OutputDir/HEMCO_diagnostics
DiagnFreq: End
Wildcard: *
Separator: /
Unit tolerance: 1
Negative values: 0
Only unitless scale factors: false
Verbose: 0
Warnings: 1
Emissions Year: 2010
```

**Comment by yantosca** [comment]
@Yuan-yuan-2021: Is there a particular inventory that you are referring to?  Is it CEDS or one of the regional inventories.  Please note that most emissions are only available for a range of certain years.  If you are outside of the time range for the emisisons, then HEMCO will pick the last year of emissions that is available.  So that could make it appear that HEMCO is not reading the latest emissions.

**Comment by yantosca** [comment]
My bad, I had it wrong.  It should have been
```
Emission year: 2010
```
Try that and see if it works better.

**Comment by yantosca** [comment]
NOTE: This is a duplicate of issue #74.
